services:

  db-raw-jobs:
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5433:5432
    volumes:
      - db-raw-jobs:/var/lib/postgresql/data

  api-raw-jobs:
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8000:8000

  db-watchdog:
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5431:5432
    volumes:
      - db-watchdog:/var/lib/postgresql/data

  api-watchdog:
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8001:8000

  scrapper:
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 6800:6800

networks:
  internal:

volumes:
  db-raw-jobs:
  db-watchdog:

secrets:
  jobs_db_name:
    external: true
  jobs_db_username:
    external: true
  jobs_db_password:
    external: true
  watchdog_db_name:
    external: true
  watchdog_db_username:
    external: true
  watchdog_db_password:
    external: true
  raw_jobs_api_username:
    external: true
  raw_jobs_api_password:
    external: true
  scrapper_api_username:
    external: true
  scrapper_api_password:
    external: true
  watchdog_api_username:
    external: true
  watchdog_api_password:
    external: true
  telegram_bot_token:
    external: true
  telegram_alert_channel:
    external: true
