services:
  api-raw-jobs:
    build: ./entremed_raw_jobs_api
    ports:
      - 8000:8000
    volumes:
      - ./entremed_raw_jobs_api:/app

  api-watchdog:
    build: ./entremed_watchdog
    ports:
      - 8001:8000
    volumes:
      - ./entremed_watchdog:/app

  scrapper:
    build: ./entremed_scrapper
    ports:
      - 6800:6800
    # volumes:
    #   - ./entremed_scrapper:/app

  # scheduler:
  #   build: ./entremed_scheduler
  #   volumes:
  #     - ./entremed_scheduler:/app


secrets:
  jobs_db_host:
    file: dev_secrets/jobs_db_host.txt
  jobs_db_name:
    file: dev_secrets/jobs_db_name.txt
  jobs_db_username:
    file: dev_secrets/jobs_db_username.txt
  jobs_db_password:
    file: dev_secrets/jobs_db_password.txt
  jobs_db_port:
    file: dev_secrets/jobs_db_port.txt
  watchdog_db_host:
    file: dev_secrets/watchdog_db_host.txt
  watchdog_db_name:
    file: dev_secrets/watchdog_db_name.txt
  watchdog_db_username:
    file: dev_secrets/watchdog_db_username.txt
  watchdog_db_password:
    file: dev_secrets/watchdog_db_password.txt
  watchdog_db_port:
    file: dev_secrets/watchdog_db_port.txt
  raw_jobs_api_username:
    file: dev_secrets/raw_jobs_api_username.txt
  raw_jobs_api_password:
    file: dev_secrets/raw_jobs_api_password.txt
  scrapper_api_username:
    file: dev_secrets/scrapper_api_username.txt
  scrapper_api_password:
    file: dev_secrets/scrapper_api_password.txt
  watchdog_api_username:
    file: dev_secrets/watchdog_api_username.txt
  watchdog_api_password:
    file: dev_secrets/watchdog_api_password.txt
  telegram_bot_token:
    file: dev_secrets/telegram_bot_token.txt
  telegram_alert_channel:
    file: dev_secrets/telegram_alert_channel.txt
